### PR TITLE
Events do_actions_completed_before & donors_group_user_add_before

### PR DESCRIPTION
**Pull request by kasimi**
Great extension, thanks for your work!

I needed some custom handling when a donation is made so I added two events to your code. Let me know if you want me to send PRs for other events in case there will be more places I need to hook into in the future. It may be useful for other developers too.

Also let me know if you need me to adjust anything in this PR to fit your needs.

### CODE REVIEW

**Review by Skouat — CHANGES_REQUESTED** [review]
Thx for your contribution.

I've only two requests...
1/ As they are the first events, please could you create a file named `events.md` on `/docs`? (eg: https://github.com/phpbb/phpbb/blob/master/phpBB/docs/events.md) 

2/ On your events docs comments, please could you convert all tab by spaces?

**Comment by kasimi** [comment]
No problem, I converted tabs to spaces. The `events.md` you linked is only for template events. Do you have an example how you want PHP events documented?

**Comment by kasimi** [comment]
I added the variable `can_use_autogroup` to the event `skouat.ppde.donors_group_user_add_before` so that event handlers can abort or force adding the user to the group.

**Comment by Skouat** [comment]
Please, could you add the `dispatcher` doc comments in the `construtor()`? (L116 to L122)

Regarding the events docs... you can use the same structure. This is only to centralize the list of events available in this extension.
eg: 
> skouat.ppde.donors_group_user_add_before
> ===
> * Location: ext/skouat/ppde/controller/ipn_listener.php
> * Since: 1.0.3
> * Purpose: Modify data before a user is added to the donors group

It remains "tab" on L937 and L981, between `@var	array`
And on L980, between `can_use_autogroup	Whether`

**Comment by Skouat** [comment]
> I added the variable can_use_autogroup to the event `skouat.ppde.donors_group_user_add_before` so that event handlers can abort or force adding the user to the group.

IMO, it doesn't make sense to place this event before the `if` statement.
Maybe it would be better to split it into two events. What do you think?
I ask because I do not really know how the event system works or could be used. :/

**Review by Skouat — APPROVED** [review]

**Comment by kasimi** [comment]
In my board I need to check additional conditions of the user that has just donated, and only if these additional conditions are true the user should be added to the group. In my event handler method I do this:

    $event['can_use_autogroup'] = $event['can_use_autogroup'] && $this->additional_conditions();

I'm not sure how you could solve this without placing the event before the `if`.

**Comment by Skouat** [comment]
> I'm not sure how you could solve this without placing the event before the `if`.

By letting your initial code in the `if` statement and creating a new event before the `if`? Only to change the `can_use_autogroup` status.
if your conditions return `true`, the event inside the `if` will be loaded and usable.

As I said above, I don't know how the events system really works. Maybe I'm wrong.

**Comment by kasimi** [comment]
Sure, that would work. From a usability point of view there's no difference. Extension developers wouldn't gain nor lose control over the execution flow either way which is why I don't see a point in splitting it up.

Let me know if I should go ahead and do it anyway.

**Comment by kasimi** [comment]
Quick followup: using two events with the first event allowing access to only `can_use_autogroup`, the handler method doesn't have access to the other variables which might be needed to determine whether or not the user can use autogroup, i.e. the new value of `can_use_autogroup`. For this reason I think using one event that has all the variables makes more sense.

**Comment by Skouat** [comment]
> For this reason I think using one event that has all the variables makes more sense.

indeed.

Thanks again for your contribution and feel free to suggest new events.
Cheers.

**Pull request merged**
