### PR TITLE
Prevent image from stretching past 100%

### PR DESCRIPTION
**Pull request by JmzTaylor**
This won't change the numbers displayed.  Only the progress bar not going past 100%

### CODE REVIEW

**Comment by Skouat** [comment]
Hi,
I'm not sure that it's necessary,
The class `progress`, in the parent DIV, already defines the width to `100%`.
And, in the case this PR is approved, you must apply the same change on the line 30.

**Comment by JmzTaylor** [comment]
The issue is that when prog-color is > 100% it squares off the right side of the div instead of rounding.  I will show screenshot in an hour or 2

**Comment by JmzTaylor** [comment]
I apologize.  Im going to close this.  Loaded it up on prosilver and it works correctly.  Something was interferring in my theme I guess.

**Comment by Skouat** [comment]
Feel free to open a ticket here or on phpbb.com.
Maybe there is something to fix to prevent this issue with other style.

**Comment by JmzTaylor** [comment]
Well this commit is what made it look right.  So I will just keep it this
way locally.  Thanks though

**Pull request closed without merging**
